name: "CI - Build Tools"

on:
  push:
    branches: [ "main" ]
    paths:
      - "build-infra/**"
      - "build-logic/**"
      - ".github/workflows/ci-build-tools.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "build-infra/**"
      - "build-logic/**"
      - ".github/workflows/ci-build-tools.yml"

jobs:
  validate-build-tools:
    name: "Validate Build Tools"
    runs-on: ubuntu-latest

    steps:
      - name: "â˜ï¸ Checkout"
        uses: actions/checkout@v4

      - name: "ğŸ”§ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: "ğŸ”§ Setup Gradle"
        uses: gradle/actions/setup-gradle@v3

      - name: "âš™ï¸ Build and Test build-infra"
        run: ./gradlew :build-infra:build

      - name: "âš™ï¸ Build and Test build-logic"
        run: ./gradlew :build-logic:build
