# .github/workflows/ci.yml
name: "CI - Application Build"

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "build-infra/**"
      - "build-logic/**"
      - ".github/workflows/ci-build-tools.yml"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "build-infra/**"
      - "build-logic/**"
      - ".github/workflows/ci-build-tools.yml"

jobs:
  build-application:
    name: "Build and Test Application"
    runs-on: ubuntu-latest

    steps:
      - name: "â˜ï¸ Checkout"
        uses: actions/checkout@v4

      - name: "ğŸ”§ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: "ğŸ”§ Setup Gradle"
        uses: gradle/actions/setup-gradle@v3

      - name: "âš™ï¸ Build and Test"
        # The 'build' task will trigger 'test', 'detekt', and 'jacocoTestReport'
        # because of how the convention plugins are set up.
        run: ./gradlew build

      - name: "ğŸ“Š Upload Build Reports"
        if: always() # This ensures reports are uploaded even if a step fails
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: |
            **/build/reports/tests/test/**
            **/build/reports/detekt/**
            **/build/reports/jacoco/test/**
